/*
 * Pre-baked AI content for the static public demo.
 *
 * In the live version, the health read, decline post-mortem, and chat are
 * generated by Claude at runtime. For a public, keyless deployment these are
 * frozen here — each one written against that client's actual computed numbers,
 * so the demo loads instantly with zero API key and zero cost.
 *
 * Keyed by client id (c0..c15). D-graded clients (c6, c10) also carry a postmortem.
 */

export const CHAT_PROMPTS = [
  "Why this grade?",
  "What's the biggest lever?",
  "How much revenue is at risk?",
];

export const PREBAKED = {
  c0: {
    read: "Larkspur holds a firm A (88) and has been rock-steady all year, with a projected A next quarter. Its strength is broad — resident adoption at 90% and autopay at 72% anchor a 94 Product score — and no lens dips below 85. With effectively no processing volume at risk, the play here isn't rescue but reference: Larkspur is a candidate for a case study or an expansion conversation.",
    chat: [
      { q: "Why this grade?", a: "An A at 88, because it's strong across all four lenses with no weak point — Product leads at 94 on 90% resident adoption, and even its lowest lens, Revenue, sits at 85. It's also been flat-stable all year, which is exactly what you want from a top account." },
      { q: "What's the biggest lever?", a: "There's little to fix — the marginal move is deepening what already works, like nudging autopay past 72%. Larkspur is better used as a reference account than treated as a project." },
      { q: "How much revenue is at risk?", a: "Effectively none — at an 88 score the at-risk model returns roughly $0 against its $5.31M quarterly TPV. This account isn't a retention risk; it's an expansion opportunity." },
    ],
  },
  c1: {
    read: "Ironwood earns an A (89) and is still climbing — up 14 points across the year and projected to reach the mid-90s next quarter. Growth is the story: TPV is maxed out and net units keep expanding, giving it an 89 Revenue score. Nothing is at risk here; the lever is to lean in — Ironwood looks like an expansion and advocacy account, not a defensive one.",
    chat: [
      { q: "Why this grade?", a: "An A at 89, earned by momentum — up from 75 in Q1 as TPV maxed out and net units kept expanding, which gives it an 89 Revenue lens. All four lenses sit in the high 80s." },
      { q: "What's the biggest lever?", a: "Lean into growth rather than defense — Ironwood is projected to hit the mid-90s, so the play is expansion and advocacy, not repair." },
      { q: "How much revenue is at risk?", a: "None to speak of — at an 89 score the model shows ~$0 at risk against a maxed $6.4M TPV base. The opportunity here is upside, not exposure." },
    ],
  },
  c2: {
    read: "Meridian is a B (72) but sliding — it's shed 14 points since Q1 and is projected to cross into C next quarter. The drag is on the Revenue lens (68, now a C), with net units and TPV softening faster than the rest of the account. With about $604k of quarterly volume at risk, this is the textbook intervene-now case: a QBR to shore up expansion before the grade slips would protect the most value per unit of effort in the book.",
    chat: [
      { q: "Why this grade?", a: "A B at 72, but a slipping one — down from 86 in Q1. The Revenue lens has fallen to a C (68) as net units and TPV soften, and it's projected to cross into C next quarter." },
      { q: "What's the biggest lever?", a: "Shore up the Revenue lens before it drags the grade under — an expansion-focused QBR to stabilize net units is the highest-value move, because this is the account closest to a downgrade." },
      { q: "How much revenue is at risk?", a: "About $604k of quarterly volume, and it's rising as the grade slips — which is exactly why Meridian is the book's clearest intervene-now case." },
    ],
  },
  c3: {
    read: "Cobalt sits at a stable B (76) and is holding — even ticking up slightly, with a projected B next quarter. It's a well-balanced account, every lens between 74 and 78, led by a 78 Risk score on low delinquency and chargebacks. Around $502k of volume carries nominal risk; the lever is gentle — nudging resident adoption (78%) upward is the cleanest path from a high-B toward A.",
    chat: [
      { q: "Why this grade?", a: "A stable B at 76, well-balanced — every lens between 74 and 78, with Risk highest at 78 on low delinquency and chargebacks. It's held steady and even ticked up this quarter." },
      { q: "What's the biggest lever?", a: "Push resident adoption above its current 78% — that's the cleanest path from a high-B toward A, lifting the Product and Revenue lenses together." },
      { q: "How much revenue is at risk?", a: "Modest — around $502k, more nominal than urgent given the account is stable and projected to stay a B." },
    ],
  },
  c4: {
    read: "Harborview holds a B (71) and has stabilized after a strong Q2, with a flat-to-slightly-up projection. Its soft spot is the Revenue lens (63, a C), dragged by a smaller TPV base rather than any health problem — Product and Risk both sit in solid B territory. With ~$508k at risk, the lever is growth, not repair: expanding processing volume with this account would lift the one lens holding it back.",
    chat: [
      { q: "Why this grade?", a: "A B at 71. The one soft lens is Revenue at 63 (a C), but that's driven by a smaller $2.99M TPV base rather than any health issue — Product and Risk are both solid B's." },
      { q: "What's the biggest lever?", a: "Grow processing volume — because the weak lens is size-driven, expanding TPV would lift the exact lens holding the grade down." },
      { q: "How much revenue is at risk?", a: "About $508k of quarterly volume, and it's stable — the projection is flat-to-slightly-up, so this reads more as a growth account than a risk one." },
    ],
  },
  c5: {
    read: "Sagebrook grades a C (59), but the trajectory is the headline — up 25 points since Q1 and still climbing toward a mid-C next quarter. The lagging lens is Revenue (49), held down by a small TPV base, while Product and Operational have already recovered into the 60s. With ~$472k at risk, this is a momentum account: keep the recovery going and it's a B-in-waiting rather than a churn concern.",
    chat: [
      { q: "Why this grade?", a: "A C at 59, but a fast-rising one — up 25 points since Q1. Revenue (49) still lags on a small TPV base, while Product and Operational have already climbed into the 60s." },
      { q: "What's the biggest lever?", a: "Keep the recovery momentum going — the account is trending toward a B on its own, so the move is to sustain the adoption gains rather than fight fires." },
      { q: "How much revenue is at risk?", a: "Around $472k, but the trajectory matters more than the level here — this reads as a B-in-waiting, not a churn concern." },
    ],
  },
  c6: {
    read: "Northgate has fallen to a D (26) and is still dropping, with every lens now in the 20s. The steepest damage is operational and revenue — payment success has slid to 91.3% and support tickets spiked to 31 per 1k while net units collapsed. With $1.57M of quarterly volume at risk, this is a full escalation: the near-term lever is stabilizing payment success and ticket load before any revenue conversation can land.",
    postmortem: "Northgate's decline turned sharply in Q4, when the composite fell from the mid-30s into the 20s. The signature was operational before it was financial: support tickets jumped from 20 to 31 per 1k transactions and payment success slipped from 94.3% to 91.3%, and only then did net units added collapse from +135 to +27. The lesson for the book — when a still-healthy account shows rising tickets and softening payment success in the same quarter, treat it as an early churn signal and intervene before the revenue metrics confirm it.",
    chat: [
      { q: "Why this grade?", a: "A D at 26, with all four lenses in the 20s. It collapsed from 50 in Q1, and the sharpest damage came in Q4 — payment success fell to 91.3% and support tickets spiked to 31 per 1k while net units cratered." },
      { q: "What's the biggest lever?", a: "Stabilize operations first — payment success and ticket load — before any revenue conversation. The account can't be repaired financially while the operational base is failing." },
      { q: "How much revenue is at risk?", a: "$1.57M of quarterly volume — the largest exposure in the book short of Elmcrest. This is a full escalation, not a nudge." },
    ],
  },
  c7: {
    read: "Willowmere is a flat C (57) — no real movement all year and a projected C next quarter. Nothing is failing outright, but nothing is strong either: every lens clusters in the mid-50s, with delinquency and chargebacks keeping Risk at 56. Because it's a larger account, ~$1.34M of volume sits at risk despite the middling grade — making it a high-value target to push from stagnant-C toward B via a focused adoption and delinquency effort.",
    chat: [
      { q: "Why this grade?", a: "A flat C at 57 — nothing failing, nothing strong. Every lens clusters in the mid-50s, with delinquency and chargebacks holding Risk at 56. It hasn't moved materially all year." },
      { q: "What's the biggest lever?", a: "A focused adoption-and-delinquency push — because it's a larger account, moving it from stagnant-C to B protects a lot of value per unit of effort." },
      { q: "How much revenue is at risk?", a: "Higher than the grade suggests — about $1.34M, because Willowmere is a sizeable account. That size is what makes a middling C worth prioritizing." },
    ],
  },
  c8: {
    read: "Brightpath is the portfolio's standout — an A (92) climbing toward the high-90s, strong on every lens (94 Product, 93 Risk). Retention is exceptional at 123% NRR and delinquency is negligible. Zero volume at risk; the only 'action' is to study what's working here and treat Brightpath as the benchmark and reference account for the rest of the book.",
    chat: [
      { q: "Why this grade?", a: "The book's top grade — an A at 92 and still climbing, strong on every lens (94 Product, 93 Risk) with exceptional 123% NRR and near-zero delinquency." },
      { q: "What's the biggest lever?", a: "Nothing defensive — Brightpath is the benchmark. Use it as the reference account and expansion template for the rest of the portfolio." },
      { q: "How much revenue is at risk?", a: "Zero — a 92 score returns no at-risk volume. This is pure upside, not exposure." },
    ],
  },
  c9: {
    read: "Kestrel holds a steady B (73), essentially flat across the year with a projected B next quarter. It's evenly balanced — every lens between 71 and 75 — with no single weak point and no single standout. About $639k of volume carries modest risk; the cleanest lever toward A is lifting resident adoption (76%) and autopay, which would pull the Product and Revenue lenses up together.",
    chat: [
      { q: "Why this grade?", a: "A steady B at 73, evenly balanced — every lens between 71 and 75, essentially flat all year with no weak point and no standout." },
      { q: "What's the biggest lever?", a: "Lift resident adoption and autopay together — that pulls Product and Revenue up in tandem and is the cleanest route toward A." },
      { q: "How much revenue is at risk?", a: "Around $639k of quarterly volume — modest, consistent with a stable B that isn't going anywhere fast." },
    ],
  },
  c10: {
    read: "Elmcrest has dropped to a D (31) and continues to slide, with all four lenses in the low 30s. The decline set in early — autopay enrollment and NRR fell from Q2 while chargebacks climbed toward 1.77%. With the largest exposure in the book at $1.63M of quarterly volume, Elmcrest is a top-priority escalation: the Risk lens (chargebacks, delinquency) is where stabilization has to start.",
    postmortem: "Elmcrest's slide began early, in Q2, rather than in a late collapse. The leading signature was product-and-risk: autopay enrollment fell from 52% to 32% and chargebacks climbed from 1.13% to 1.77%, with net revenue retention eroding from 106% to 94% in parallel. The transferable lesson — a simultaneous drop in autopay adoption and a rise in chargebacks is an early-warning pattern worth flagging in any B or C account, well before it shows up as retention loss.",
    chat: [
      { q: "Why this grade?", a: "A D at 31, all lenses in the low 30s. It's been declining since Q2 — autopay and NRR fell while chargebacks climbed toward 1.77% — and it's still sliding." },
      { q: "What's the biggest lever?", a: "Start with the Risk lens — chargebacks and delinquency — since that's where the decline originated. Financial recovery isn't possible until the risk base is stabilized." },
      { q: "How much revenue is at risk?", a: "The book's single largest exposure — $1.63M of quarterly volume. Top-priority escalation." },
    ],
  },
  c11: {
    read: "Vantage grades a C (65) with a volatile but upward path — swinging quarter to quarter yet netting a projected high-C. Product has already reached B (70) on decent adoption; the softness is in Revenue and the choppiness itself. With ~$716k at risk, the lever is consistency: smoothing the operational swings (success rate, tickets) would convert a jumpy C into a dependable B.",
    chat: [
      { q: "Why this grade?", a: "A C at 65 with a volatile path — it swings quarter to quarter but nets upward, and Product has already reached B (70) on decent adoption. The choppiness itself is part of what caps the grade." },
      { q: "What's the biggest lever?", a: "Smooth the operational swings — success rate and tickets — since consistency is what separates this jumpy C from a dependable B." },
      { q: "How much revenue is at risk?", a: "About $716k. The level is manageable; the volatility is the real watch-item." },
    ],
  },
  c12: {
    read: "Copperline is a rock-solid A (91), edging higher all year with best-in-class 125% NRR and a 93 Risk score. Every lens sits at 89 or above and nothing is at risk. Like the other A's, the move isn't defensive — Copperline is a reference and expansion account, a template for what a healthy client looks like.",
    chat: [
      { q: "Why this grade?", a: "An A at 91, edging higher all year, with best-in-class 125% NRR and a 93 Risk lens. Every lens is 89 or above." },
      { q: "What's the biggest lever?", a: "None defensive — like the other A's, Copperline is a reference and expansion account, a template for a healthy client." },
      { q: "How much revenue is at risk?", a: "Zero at-risk volume at this score. The conversation here is growth, not retention." },
    ],
  },
  c13: {
    read: "Fernbank is a stable C (60), barely moving all year. Its weakest lens is Product (57) — resident adoption at 66% and autopay at 51% lag the healthier accounts — while Risk (64) is its relative strength. With ~$1.19M at risk given its size, the highest-leverage move is a targeted adoption push: Product is both its lowest lens and the most improvable one.",
    chat: [
      { q: "Why this grade?", a: "A stable C at 60, barely moving all year. Product is its weakest lens (57) — adoption at 66% and autopay at 51% trail healthier accounts — while Risk (64) is its relative strength." },
      { q: "What's the biggest lever?", a: "A targeted adoption push — Product is both its lowest lens and its most improvable, so that's where a point of effort moves the grade most." },
      { q: "How much revenue is at risk?", a: "Around $1.19M given its size — a mid-grade account that's worth attention mainly because of the volume behind it." },
    ],
  },
  c14: {
    read: "Slate & Oak grades a C (57) and is recovering well — up 15 points since Q1. Revenue (49) is the laggard, but it's a small-TPV artifact rather than a health issue; Product and Operational have climbed into the 60s. With only ~$387k at risk, this is a low-stakes momentum account — keep the recovery going and it graduates toward B on its own.",
    chat: [
      { q: "Why this grade?", a: "A C at 57 and recovering — up 15 points since Q1. Revenue (49) lags, but that's a small-TPV artifact rather than a health problem; Product and Operational have climbed into the 60s." },
      { q: "What's the biggest lever?", a: "Sustain the recovery — the account is climbing on its own, so the move is to keep adoption trending up rather than intervene heavily." },
      { q: "How much revenue is at risk?", a: "Only about $387k — the lowest-stakes account in the watch list, which is why it's a keep-an-eye-on rather than an escalation." },
    ],
  },
  c15: {
    read: "Tidewater has fallen from an A-level 89 to a C (68) — the sharpest decliner among still-salvageable accounts — and is projected to keep sliding. The erosion is broad, but Revenue and Operational have taken the hardest hits while Product still clings to a 70. With ~$903k at risk, Tidewater is the top 'catch it now' case in the watch list: it retains enough strength to recover if the slide is arrested this quarter.",
    chat: [
      { q: "Why this grade?", a: "A C at 68 — but the story is the fall from an A-level 89. It's the sharpest decliner among still-salvageable accounts, with Revenue and Operational hit hardest while Product still holds a 70." },
      { q: "What's the biggest lever?", a: "Arrest the slide this quarter — Tidewater retains enough underlying strength to recover if the decline is caught now, which makes it the top 'catch it now' case in the book." },
      { q: "How much revenue is at risk?", a: "About $903k — the largest among the salvageable accounts, which is exactly why it tops the needs-attention strip." },
    ],
  },
};
